fxc.exe/T vs_5_1 /E VSMain /Fh CompiledShader/VS_UV.fxc Shader/VS_UV.hlsl
fxc.exe/T vs_5_1 /E VSMain /Fh CompiledShader/VS_UV_Shadow.fxc Shader/VS_UV_Shadow.hlsl
fxc.exe/T vs_5_1 /E VSMain /Fh CompiledShader/VS_UVAttribute.fxc Shader/VS_UVAttribute.hlsl
fxc.exe/T vs_5_1 /E VSMain /Fh CompiledShader/VS_UVColor.fxc Shader/VS_UVColor.hlsl
fxc.exe/T vs_5_1 /E VSMain /Fh CompiledShader/VS_UVFog.fxc Shader/VS_UVFog.hlsl
fxc.exe/T vs_5_1 /E VSMain /Fh CompiledShader/VS_UVNormal.fxc Shader/VS_UVNormal.hlsl
fxc.exe/T vs_5_1 /E VSMain /Fh CompiledShader/VS_UVNormal_Shadow.fxc Shader/VS_UVNormal_Shadow.hlsl
fxc.exe/T vs_5_1 /E VSMain /Fh CompiledShader/VS_UVNormalAttribute.fxc Shader/VS_UVNormalAttribute.hlsl
fxc.exe/T vs_5_1 /E VSMain /Fh CompiledShader/VS_UVNormalFog.fxc Shader/VS_UVNormalFog.hlsl
fxc.exe/T vs_5_1 /E VSMain /Fh CompiledShader/VS_UVNormalFog_Shadow.fxc Shader/VS_UVNormalFog_Shadow.hlsl
fxc.exe/T vs_5_1 /E VSMain /Fh CompiledShader/VS_UVNormalPhong_Shadow.fxc Shader/VS_UVNormalPhong_Shadow.hlsl
fxc.exe/T vs_5_1 /E VSMain /Fh CompiledShader/VS_UVNormalPosition.fxc Shader/VS_UVNormalPosition.hlsl
fxc.exe/T vs_5_1 /E VSMain /Fh CompiledShader/VS_UVNormalTangent.fxc Shader/VS_UVNormalTangent.hlsl
fxc.exe/T vs_5_1 /E VSMain /Fh CompiledShader/VS_UVNormalTangent_Shadow.fxc Shader/VS_UVNormalTangent_Shadow.hlsl
fxc.exe/T vs_5_1 /E VSMain /Fh CompiledShader/VS_UVPosition.fxc Shader/VS_UVPosition.hlsl
fxc.exe/T vs_5_1 /E VSMain /Fh CompiledShader/VS_ImmediateParticle.fxc Shader/VS_ImmediateParticle.hlsl
fxc.exe/T vs_5_1 /E VSMain /Fh CompiledShader/VS_UVFog_Shadow.fxc Shader/VS_UVFog_Shadow.hlsl
fxc.exe/T vs_5_1 /E VSMain /Fh CompiledShader/VS_UVNormalColorFog.fxc Shader/VS_UVNormalColorFog.hlsl
fxc.exe/T vs_5_1 /E VSMain /Fh CompiledShader/VS_UVNormalColorFog_Shadow.fxc Shader/VS_UVNormalColorFog_Shadow.hlsl
fxc.exe/T vs_5_1 /E VSMain /Fh CompiledShader/VS_UVNormalColor.fxc Shader/VS_UVNormalColor.hlsl
fxc.exe/T vs_5_1 /E VSMain /Fh CompiledShader/VS_UVNormalPhong.fxc Shader/VS_UVNormalPhong.hlsl
fxc.exe/T vs_5_1 /E VSMain /Fh CompiledShader/VS_ShadowMap.fxc Shader/VS_ShadowMap.hlsl
fxc.exe/T vs_5_1 /E VSMain /Fh CompiledShader/VS_ShadowMap_UV.fxc Shader/VS_ShadowMap_UV.hlsl

fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_Grid.fxc Shader/PS_Grid.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_Grid_Shadow.fxc Shader/PS_Grid_Shadow.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_Grid_worldColor.fxc Shader/PS_Grid_worldColor.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_GridFog.fxc Shader/PS_GridFog.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_OnlyMaterial.fxc Shader/PS_OnlyMaterial.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_OnlyMaterial_BloomSource.fxc Shader/PS_OnlyMaterial_BloomSource.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_PostEffect_GausBlur.fxc Shader/PS_PostEffect_GausBlur.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_PostEffect_GausBlurFloat2.fxc Shader/PS_PostEffect_GausBlurFloat2.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_ShadowMap.fxc Shader/PS_ShadowMap.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_ShadowMap_UV.fxc Shader/PS_ShadowMap_UV.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_SpriteAnimation.fxc Shader/PS_SpriteAnimation.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_UVColor.fxc Shader/PS_UVColor.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_UVColor_Shadow.fxc Shader/PS_UVColor_Shadow.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_UVColorFog.fxc Shader/PS_UVColorFog.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_UVColorFog_Shadow.fxc Shader/PS_UVColorFog_Shadow.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_UVDepth.fxc Shader/PS_UVDepth.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_UV.fxc Shader/PS_UV.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_UVFog.fxc Shader/PS_UVFog.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_UVFog_Shadow.fxc Shader/PS_UVFog_Shadow.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_UVNormal.fxc Shader/PS_UVNormal.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_UVNormal_Shadow.fxc Shader/PS_UVNormal_Shadow.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_UVNormalColor.fxc Shader/PS_UVNormalColor.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_UVNormalColor_Shadow.fxc Shader/PS_UVNormalColor_Shadow.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_UVNormalColorFog.fxc Shader/PS_UVNormalColorFog.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_UVNormalColorFog_Shadow.fxc Shader/PS_UVNormalColorFog_Shadow.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_UVNormalFog.fxc Shader/PS_UVNormalFog.hlsl
fxc.exe/T ps_5_1 /E PSMain /Fh CompiledShader/PS_UVNormalFog_Shadow.fxc Shader/PS_UVNormalFog_Shadow.hlsl

fxc.exe/T gs_5_1 /E GSMain /Fh CompiledShader/GS_OutLine.fxc Shader/GS_OutLine.hlsl
fxc.exe/T gs_5_1 /E GSMain /Fh CompiledShader/GS_PointToCube.fxc Shader/GS_PointToCube.hlsl
fxc.exe/T gs_5_1 /E GSMain /Fh CompiledShader/GS_PointToCube_WithoutUV.fxc Shader/GS_PointToCube_WithoutUV.hlsl
fxc.exe/T gs_5_1 /E GSMain /Fh CompiledShader/GS_PointToPlane.fxc Shader/GS_PointToPlane.hlsl
fxc.exe/T gs_5_1 /E GSMain /Fh CompiledShader/GS_PointToTriPolygon_WithoutUV.fxc Shader/GS_PointToTriPolygon_WithoutUV.hlsl

